name: textling
on: [pull_request]
jobs:
  build:
    name: check textlint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: yarn install
      - name: Check Textlint
        run: yarn run textlint
